experiment_name: early_stop_test

model:
  type: models/Adrian.yaml
  pretrained: false

paths:
  train: dataset_final_boxes_yolo/train.txt
  val: dataset_final_boxes_yolo/val.txt
  test: dataset_final_boxes_yolo/test.txt

training:
  batch_size: 8
  epochs: 120
  log_interval: 100
  early_stop_count: 1

optimizer:
  type: AdamW
  lr: 0.1
  lr_scheduler: fixed
  weight_decay: 0.0005
  momentum: 0.9

freeze:
  backbone_layers: 0
  dfl: false

augmentation: none
dataset_size: 1

loss:
  type: spatial
  lambda_rate: 1
