augmentation: final
batch_size: 8
epochs: 100
experiment_name: optimzer_config_pretrained_lamda_rate40
freeze_backbone_layers: 11
freeze_dfl: false
lamda_rate: 40
log_interval: 10
lr_scheduler: fixed
model: custom_yolo.yaml
optimizer: AdamW
pretrained: true
save_interval: 30
save_path: weights
test_data_path: /home/dl01e25/dataset_final_boxes_yolo/test_old.txt
train_data_path: /home/dl01e25/dataset_final_boxes_yolo/train_old.txt
use_ema: false
val_data_path: /home/dl01e25/dataset_final_boxes_yolo/val_old.txt




augmentation: final
batch_size: 8
epochs: 100
experiment_name: jagerloss_no_prop_config_pretrained_lamda_rate40
freeze_backbone_layers: 11
freeze_dfl: false
lamda_rate: 40
log_interval: 10
loss_type: spatial_consistency
lr: 0.01
lr_scheduler: fixed
model: custom_yolo.yaml
momentum: 0.99
optimizer: AdamW
pretrained: true
save_interval: 30
save_path: weights
test_data_path: /home/dl01e25/dataset_final_boxes_yolo/test_old.txt
train_data_path: /home/dl01e25/dataset_final_boxes_yolo/train_old.txt
use_ema: false
val_data_path: /home/dl01e25/dataset_final_boxes_yolo/val_old.txt
weight_decay: 0.001
