
EXPERIMENT_1A_LABELS = {
    "phase1a_sgd_standard": "SGD Standard",
    "phase1a_sgd_conservative": "SGD Conservative",
    "phase1a_adamw_standard": "AdamW Standard",
    "phase1a_adamw_conservative": "AdamW Conservative",
    "phase1a_adamw_aggressive": "AdamW Aggressive",
}

COLORS_1A = {
    "phase1a_sgd_standard": "#e74c3c",
    "phase1a_sgd_conservative": "#c0392b",
    "phase1a_adamw_standard": "#3498db",
    "phase1a_adamw_conservative": "#2980b9",
    "phase1a_adamw_aggressive": "#9b59b6",
}

EXPERIMENT_1B_LABELS = {
    # "phase1b_not_frozen": "Not Frozen",
    # "phase1b_fully_frozen": "Fully Frozen",
    # "phase1b_frozen_half": "Frozen Half",
    # "phase2_no_augmentation_20_images": "Phase 2 No Augmentation (20 Images)",
    # "phase2_no_augmentation_40_images": "Phase 2 No Augmentation (40 Images)",
    # "phase2_no_augmentation_80_images": "Phase 2 No Augmentation (80 Images)",
    # "phase2_no_augmentation_all_images": "Phase 2 No Augmentation (All Images)",
    # "phase2_light_augmentation_20_images": "Phase 2 Light Augmentation (20 Images)",
    # "phase2_light_augmentation_40_images": "Phase 2 Light Augmentation (40 Images)",
    # "phase2_light_augmentation_80_images": "Phase 2 Light Augmentation (80 Images)",
    # "phase2_light_augmentation_all_images": "Phase 2 Light Augmentation (All Images)",
    # "phase2_geo_augmentation_20_images": "Phase 2 Geo Augmentation (20 Images)",
    # "phase2_geo_augmentation_40_images": "Phase 2 Geo Augmentation (40 Images)",
    # "phase2_geo_augmentation_80_images": "Phase 2 Geo Augmentation (80 Images)",
    # "phase2_geo_augmentation_all_images": "Phase 2 Geo Augmentation (All Images)",
    # "phase2_full_augmentation_20_images": "Phase 2 Full Augmentation (20 Images)",
    # "phase2_full_augmentation_40_images": "Phase 2 Full Augmentation (40 Images)",
    # "phase2_full_augmentation_80_images": "Phase 2 Full Augmentation (80 Images)",
    # "phase2_full_augmentation_all_images": "Phase 2 Full Augmentation (All Images)",
    # "full_aug_dfl_freeze": "Full Augmentation + FreezeDFL",
    # "dfl_frozen": "DFL Frozen",
    # "dfl_unfrozen": "DFL Unfrozen",
    # "phase1b_not_frozen_timed": "Not Frozen",
    # "phase1b_frozen_half_timed": "Frozen Half",
    # "phase1b_fully_frozen_timed": "Fully Frozen",
    # "full_augmentation_all_images": "Full Augmentation (All Images) 300 epochs",
    # "geo_augmentation_all_images": "Geo Augmentation (All Images) 300 epochs",
    # "light_augmentation_all_images": "Light Augmentation (All Images) 300 epochs",
    # "no_augmentation_all_images": "No Augmentation (All Images) 300 epochs",
    # "phase1b_not_frozen_timed_mini": "Not Frozen Mini",
    # "phase1b_frozen_half_timed_mini": "Frozen Half Mini",
    # "phase1b_fully_frozen_timed_mini": "Fully Frozen Mini",
    # "phase1b_frozen_all_timed_mini": "Frozen All Mini",
    # "new_dataset": "New Dataset",
    # "old_dataset": "Old Dataset",
    # "new_dataset_new_gains": "New Dataset New Gains",
    # "old_dataset_new_gains": "Old Dataset New Gains",
    # "normal_loss": "Normal Loss",
    # "spatial_loss": "Spatial Consistency Loss",
    "dataset_size_small_dataset_size1_0000": "Small Dataset Size 1,000",
    "dataset_size_small_dataset_size0_5000": "Small Dataset Size 0.5",
    "dataset_size_small_dataset_size0_2500": "Small Dataset Size 0.25",
    "dataset_size_small_dataset_size0_1250": "Small Dataset Size 0.125",
    "dataset_size_pretrained_dataset_size1_0000": "Pretrained Dataset Size 1,000",
    "dataset_size_pretrained_dataset_size0_5000": "Pretrained Dataset Size 0.5",
    "dataset_size_pretrained_dataset_size0_2500": "Pretrained Dataset Size 0.25",
    "dataset_size_pretrained_dataset_size0_1250": "Pretrained Dataset Size 0.125",
}

COLORS_1B = {
    # "phase1b_not_frozen": "#d61c3b",
    # "phase1b_fully_frozen": "#11d663",
    # "phase1b_frozen_half": "#1440d1",
    # "phase2_no_augmentation_20_images": "#ff9d00ff",
    # "phase2_no_augmentation_40_images": "#c27800ff",
    # "phase2_no_augmentation_80_images": "#925a00ff",
    # "phase2_no_augmentation_all_images": "#553400ff",
    # "phase2_light_augmentation_20_images": "#3cff00",
    # "phase2_light_augmentation_40_images": "#29b100",
    # "phase2_light_augmentation_80_images": "#1b7200",
    # "phase2_light_augmentation_all_images": "#114900",
    # "phase2_geo_augmentation_20_images": "#8e44ad",
    # "phase2_geo_augmentation_40_images": "#2c3e50",
    # "phase2_geo_augmentation_80_images": "#d35400",
    # "phase2_geo_augmentation_all_images": "#7f8c8d",
    # "phase2_full_augmentation_20_images": "#3498db",
    # "phase2_full_augmentation_40_images": "#2980b9",
    # "phase2_full_augmentation_80_images": "#1abc9c",
    # "phase2_full_augmentation_all_images": "#0b20db",
    # "full_aug_dfl_freeze": "#e42d15",
    # "dfl_frozen": "#e42d15",
    # "dfl_unfrozen": "#27ae60",
    # "phase1b_not_frozen_timed": "#d61c3b",
    # "phase1b_frozen_half_timed": "#1440d1",
    # "phase1b_fully_frozen_timed": "#11d663",
    # "full_augmentation_all_images": "#FF0000",
    # "geo_augmentation_all_images": "#ff00aa",
    # "light_augmentation_all_images": "#260ff1",
    # "no_augmentation_all_images": "#ffee00",
    # "phase1b_not_frozen_timed_mini": "#d61c3b",
    # "phase1b_frozen_half_timed_mini": "#1440d1",
    # "phase1b_fully_frozen_timed_mini": "#11d663",
    # "phase1b_frozen_all_timed_mini": "#ff8800",
    # "new_dataset": "#22aa22",
    # "old_dataset": "#aa2222",
    # "new_dataset_new_gains": "#2288ff",
    # "old_dataset_new_gains": "#ff8822",
    # "normal_loss": "#3498db",
    # "spatial_loss": "#e74c3c"
    "dataset_size_small_dataset_size1_0000": "#d61c3b",
    "dataset_size_small_dataset_size0_5000": "#ffae00",
    "dataset_size_small_dataset_size0_2500": "#ffe600",
    "dataset_size_small_dataset_size0_1250": "#00ff22",
    "dataset_size_pretrained_dataset_size1_0000": "#00ffff",
    "dataset_size_pretrained_dataset_size0_5000": "#0044ff",
    "dataset_size_pretrained_dataset_size0_2500": "#9900ff",
    "dataset_size_pretrained_dataset_size0_1250": "#ff00d4",
}